services:
  app:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: app:1.0.0
    container_name: app
    user: 'node'
    hostname: node
    ports:
      - '3000:3000'
    restart: 'always'
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - '5432:5432'
